reset loop_counter incase a new video is playing
ophirhan/cnsr-vlc-viewer-addon pull request #92
Opened 2021-06-21 10:41 UTC by Gal-Tch

a partial fix for issue 78:
https://github.com/ophirhan/cnsr-vlc-viewer-addon/issues/78

2021-06-21 18:13 UTC, ophirhan requested changes

2021-06-21 18:13 UTC, ophirhan commented on intf/cnsr_intf.lua
> +		current_item = vlc.playlist.get(vlc.playlist.current()) -- if a new video is playing, then we want to get the new config
Should we maybe check once every get loop interval?
meaning move lines 154-162 all of this code into the if loop_counter  == 0

2021-06-21 18:13 UTC, ophirhan commented on intf/cnsr_intf.lua
> +			sleep(SLEEP_WHILE_PARSING) -- wait for cnsr_ext to finish parsing the new cnsr file
Great idea!
but maybe use vlc.misc.mwait(vlc.misc.mdate() + <microseconds>) which doesn't hog the CPU :-P

2021-06-21 23:10 UTC, ishayhil commented
@ophirhan @Gal-Tch loop_counter is removed with #95 PR

2021-06-22 10:57 UTC, ophirhan requested changes
Maybe this needs to be re-implemented by adding tag_index = 1
when ever memory.get_written() returns true?

2021-06-22 13:45 UTC, ophirhan approved these changes

2021-06-22 13:45 UTC, merged